stages:
  - fetch
  - deploy

fetch_stats:
  image: python:3.11
  stage: fetch
  script:
    - pip install beautifulsoup4 requests
    - mkdir -p data
    - python fetch_stats.py
  artifacts:
    paths:
      - data/media_stats.json
  only:
    - schedules
    - main

pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html public/
    - cp -r data public/
  artifacts:
    paths:
      - public
  only:
    - main
